services:
  - type: web
    name: genreguru
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
